In [ ]:
import numpy as np

# Columns: [Student_ID, Study_Hours, Math_Score, Science_Score, English_Score]
data = np.array([
    [1, 2, 65, 70, 68],
    [2, 4, 78, 82, 80],
    [3, 1, 55, 60, 58],
    [4, 5, 88, 90, 85],
    [5, 3, 72, 75, 70],
    [6, 6, 92, 95, 91],
    [7, 2, 60, 64, 62],
    [8, 4, 80, 85, 83],
    [9, 3, 74, 78, 76],
    [10, 5, 89, 92, 90]
])

data.shape

(10, 5)

In [ ]:
'''
1️⃣ Extract Study Hours
Using NumPy slicing, extract only the study hours column.
'''
study_hours = data[: , 1]
study_hours


array([2, 4, 1, 5, 3, 6, 2, 4, 3, 5])

In [ ]:
'''
2️⃣ Average Score per Subject
Calculate the average score for Math, Science, and English.
'''
avg_score = data.mean(axis= 0)
avg_score[2:5]

array([75.3, 79.1, 76.3])

In [ ]:
'''
3️⃣ Find Top Performer
Find the student with the highest total score across all subjects.
'''
total_marks = data[:, 2:].sum(axis=1)

top_student_index = np.argmax(total_marks)

topper_row = data[top_student_index]
topper_id = data[top_student_index, 0]

print(f"Topper ID: {topper_id}, Total Marks: {total_marks[top_student_index]}")

Topper ID: 6, Total Marks: 278


In [ ]:
'''
4️⃣ Students Who Studied More Than 3 Hours
Filter students who studied more than 3 hours per day.
'''
filtered_stu = data[0:-1][data[0:-1, 1] > 3]
filtered_stu[0: , 0:2]

array([[2, 4],
       [4, 5],
       [6, 6],
       [8, 4]])

In [ ]:
'''
5️⃣ Total Score Per Student
Create a NumPy array containing total marks of each student.
'''
total_marks

array([203, 240, 173, 263, 217, 278, 186, 248, 228])

In [ ]:
'''
6️⃣ Students Scoring Above 85 in Math
Find student IDs where Math score > 85.
'''
math_topper = data[data[: , 2] > 85 ,0]
math_topper

array([ 4,  6, 10])

In [ ]:
'''
7️⃣ Add a New Column
Add a new column representing Average Score per Student.
'''
avg_score = data[ : , 2:5 ].mean(axis=1)
rounded_avg = np.round(avg_score , 2)
np.column_stack((data , rounded_avg))

array([[ 1.  ,  2.  , 65.  , 70.  , 68.  , 67.67],
       [ 2.  ,  4.  , 78.  , 82.  , 80.  , 80.  ],
       [ 3.  ,  1.  , 55.  , 60.  , 58.  , 57.67],
       [ 4.  ,  5.  , 88.  , 90.  , 85.  , 87.67],
       [ 5.  ,  3.  , 72.  , 75.  , 70.  , 72.33],
       [ 6.  ,  6.  , 92.  , 95.  , 91.  , 92.67],
       [ 7.  ,  2.  , 60.  , 64.  , 62.  , 62.  ],
       [ 8.  ,  4.  , 80.  , 85.  , 83.  , 82.67],
       [ 9.  ,  3.  , 74.  , 78.  , 76.  , 76.  ],
       [10.  ,  5.  , 89.  , 92.  , 90.  , 90.33]])

In [ ]:
'''
8️⃣ Standard Deviation of Scores
Calculate standard deviation for each subject.
'''
subjects_std = data[: , 2:].std(axis=0)
np.round(subjects_std , 2)

array([11.93, 11.29, 10.89])

In [ ]:
'''
9️⃣ Normalize Scores
Normalize all subject scores using Min-Max normalization.
'''
scores = data[:, 2:]

col_min = scores.min(axis=0)
col_max = scores.max(axis=0)

normalized_scores = (scores - col_min) / (col_max - col_min)

normalized_scores = np.round(normalized_scores, 2)

print(normalized_scores)

[[0.27 0.29 0.3 ]
 [0.62 0.63 0.67]
 [0.   0.   0.  ]
 [0.89 0.86 0.82]
 [0.46 0.43 0.36]
 [1.   1.   1.  ]
 [0.14 0.11 0.12]
 [0.68 0.71 0.76]
 [0.51 0.51 0.55]
 [0.92 0.91 0.97]]


In [ ]:
'''
🔟 Correlation Between Study Hours and Math Score
Compute correlation between:
'''
study_hours = data[:,1]
math_scores = data[:,2]

corr_matrix = np.corrcoef(study_hours, math_scores)

corr = corr_matrix[0,1]
print(np.round(corr , 2))

0.99
