In [26]:
import numpy as np

**ARRAY OPERATIONS**

Arithemetic operations

In [27]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [28]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [29]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [30]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [31]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [32]:
a1 // a2

array([0, 0, 0, 0, 0])

In [33]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

**Broadcasting**

In [34]:
l = [10,20,30,40]
arr = np.array(l)

In [35]:
arr +10

array([20, 30, 40, 50])

In [36]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [37]:
arr2 = arr2 +10
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

**Deep and Shallow copy**

In [38]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [39]:
slice = a[:5]
slice = slice + 10
slice

array([11, 12, 13, 14, 15])

In [40]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [41]:
a[4:6] + 10

array([15, 16])

In [42]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [43]:
a
b = a.copy()

In [44]:
b[0] = 99

In [45]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [46]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

**Matrix Operations**

In [47]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [48]:
A

array([[1, 2],
       [3, 4]])

In [49]:
B

array([[5, 6],
       [7, 8]])

In [50]:
A*B

array([[ 5, 12],
       [21, 32]])

In [51]:
A @ B

array([[19, 22],
       [43, 50]])

In [53]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [54]:
A.T

array([[1, 3],
       [2, 4]])

**Advance Array Manipulation**

In [57]:
# Stacking Array
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [58]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [59]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [61]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [62]:
# Splitting Array
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [63]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [65]:
a = np.vsplit(c,2)

In [66]:
for i in a:
  print(i)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
