In [1]:
import numpy as np

In [19]:
# Creating an array of numbers from 11 to 20 (inclusive of 11 and exclusive of 21)
arr = np.arange(11, 21)

# Displaying the created array
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [21]:
# Accessing elements from index 1 to 3 (index 4 is not included)
arr[1:4]

array([12, 13, 14])

In [7]:
arr[:5]

array([11, 12, 13, 14, 15])

In [22]:
# Accessing elements from index 3 to the end, with a step of 2 (every second element)
arr[3::2]

array([14, 16, 18, 20])

NUMPY **Indexing** and Slicing of Matrix bold text

In [23]:
# Creating an array of numbers from 1 to 30
# Then reshaping it into a 6x5 (6 rows, 5 columns) matrix
arr = np.arange(1, 31).reshape(6, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [24]:
# Accessing the element at 1st row (index 0) and 1st column (index 0)
arr[0, 0]

np.int64(1)

In [11]:
arr[0,4]

np.int64(5)

In [25]:
# Extracting a subarray:
# Rows from index 3 to 5 (i.e., 4th to 6th rows)
# Columns from index 3 to 4 (i.e., 4th to 5th columns)
slice = arr[3:6, 3:5]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [26]:
# Selecting all rows (:) and only the 3rd column (index 2)
arr[:, 2]

array([ 3,  8, 13, 18, 23, 28])

BOOLEAN Indexing

In [28]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [29]:
# Creating a boolean array where each element of 'arr' is checked for evenness
# True if the element is even, otherwise False
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [30]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])