**Basic Array Creation**

In [5]:
# Import the numpy library, commonly imported as 'np' for convenience
import numpy as np

# Create a NumPy array named 'arr' with elements 1, 2, 3, 4, 5
arr = np.array([1, 2, 3, 4, 5])

# Display the contents of the array 'arr'
arr

array([1, 2, 3, 4, 5])

In [6]:
# Create a Python list named 'a' containing mixed data types:
#   - integers: 1, 2
#   - float: 4.5
#   - string: "hello"
a = [1, 2, 4.5, "hello"]

# Display the contents of the list 'a'
print(a)

[1, 2, 4.5, 'hello']


In [ ]:
# Create a NumPy array with elements 1, 2, and 3
np.array(a)

array(['1', '2', '4.5', 'hello'], dtype='<U32')

In [ ]:
# Create a nested list 'l' containing three sublists, each representing a row of numbers
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
# Convert nested list to a 2D NumPy array for numerical operations
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Array Generation Function**

In [ ]:
# Create a NumPy array with values from 1 to 10 (exclusive) stepping by 2
arr = np.arange(1, 11, 2)

arr

array([1, 3, 5, 7, 9])

In [ ]:
# Create a 4x8 NumPy array filled with zeros
arr = np.zeros((4, 8))

arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
# Create a 6x6 NumPy array filled with ones
arr = np.ones((6, 6))

arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
# Create a NumPy array of 10 evenly spaced values starting at 1 and ending at 5
arr = np.linspace(1, 5, 10)

arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

**Random Generation Funtion**

In [ ]:
# Generate a 1D NumPy array of 5 random numbers uniformly distributed between 0 and 1
arr = np.random.rand(5)

arr

array([0.65283192, 0.04078837, 0.05106364, 0.37478239, 0.10677584])

In [ ]:
# Generate a 1D NumPy array with 10 random values sampled from a standard normal distribution (mean 0, variance 1)
arr = np.random.randn(10)

arr

array([ 0.65800308,  1.58459455, -0.40904692,  0.48878243, -1.61603642,
        2.16114737, -0.79320321,  0.2075701 ,  1.12440886,  0.69298644])

In [ ]:
# Generate an array of 10 random integers between 10 (inclusive) and 30 (exclusive)
arr = np.random.randint(10, 30, 10)

arr

array([17, 20, 29, 11, 22, 16, 12, 10, 21, 16])

**Array Attributes**

In [ ]:
# Create a 3x3 NumPy array from a nested Python list, representing a 2D matrix
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr.shape

(3, 3)

In [18]:
arr.size

9

In [19]:
arr.dtype

dtype('int64')

**Array Method**

In [20]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr.min()

np.int64(1)

In [23]:
arr.max()

np.int64(9)

In [24]:
arr.sum()

np.int64(45)

In [ ]:
# Calculate the sum of the array elements along the specified axis (0 for columns, 1 for rows)
np.sum(arr , axis=0)

array([12, 15, 18])

In [ ]:
arr.mean()

np.float64(5.0)

In [ ]:
# Calculate the standard deviation of the array 'arr'
arr.std()

np.float64(2.581988897471611)

In [ ]:
# Provide the index of the maximum value in the array
arr.argmax()

np.int64(8)

**Reshaping and Resizing**

In [ ]:
# Create a NumPy array with values from 1 to 30 (exclusive)
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
# Reshape the array 'arr' into a 6x5 matrix
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])